name: Dynamic README content injection
on:
  schedule:
    - cron: "0 * * * *"
jobs:
  update-readme-with-blog:
    name: Updates blog articles from blocs.fr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://blocs.fr/feed.xml"